version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-8082}:8082"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - skylapse-images:/data/images # Transferred images from Pi
      - skylapse-timelapses:/data/timelapses # Generated timelapse videos
    environment:
      - PI_HOST=${PI_HOST:-192.168.0.124}
      - PI_PORT=${PI_PORT:-8080}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8082}

  transfer:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: python3 services/transfer.py
    network_mode: host # Use host network for DNS resolution
    volumes:
      - skylapse-images:/data/images
      - ~/.ssh:/root/.ssh:ro # SSH keys for Pi access
    environment:
      - PI_HOST=${PI_HOST:-192.168.0.124}
      - PI_USER=${PI_USER:-nicholasmparker}
      - PI_SOURCE=${PI_SOURCE:-~/skylapse-images/}
      - LOCAL_DEST=${LOCAL_DEST:-/data/images}
      - TRANSFER_INTERVAL_MINUTES=${TRANSFER_INTERVAL_MINUTES:-5}
      - DELETE_AFTER_DAYS=${DELETE_AFTER_DAYS:-1}
    restart: unless-stopped

  processing:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: python3 -m processing.timelapse_generator
    volumes:
      - skylapse-images:/data/images
      - skylapse-timelapses:/data/timelapses
    depends_on:
      - backend
      - transfer

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:8082}
    depends_on:
      - backend

volumes:
  skylapse-images:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SKYLAPSE_IMAGES_PATH:-./data/images}
  skylapse-timelapses:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SKYLAPSE_TIMELAPSES_PATH:-./data/timelapses}
