version: "3.8"

services:
  backend:
    image: ghcr.io/nicholasmparker/skylapse/backend:main
    ports:
      - "${BACKEND_PORT:-8082}:8082"
    volumes:
      - ./backend/config.json:/app/config.json:ro
      - skylapse-images:/data/images # Transferred images from Pi
      - skylapse-timelapses:/data/timelapses # Generated timelapse videos
      - skylapse-db:/data/db # SQLite database persistence
    environment:
      - PI_HOST=${PI_HOST:-192.168.0.124}
      - PI_PORT=${PI_PORT:-8080}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8082}
      - REDIS_URL=redis://redis:6379
      - BACKEND_NAME=${BACKEND_NAME:-production} # For Pi coordination
    depends_on:
      - redis
    restart: unless-stopped

  transfer:
    image: ghcr.io/nicholasmparker/skylapse/backend:main
    command: python3 services/transfer.py
    network_mode: host # Use host network for DNS resolution
    volumes:
      - skylapse-images:/data/images
      - ~/.ssh:/root/.ssh:ro # SSH keys for Pi access
    environment:
      - PI_HOST=${PI_HOST:-192.168.0.124}
      - PI_USER=${PI_USER:-nicholasmparker}
      - PI_SOURCE=${PI_SOURCE:-~/skylapse-images/}
      - LOCAL_DEST=${LOCAL_DEST:-/data/images}
      - TRANSFER_INTERVAL_MINUTES=${TRANSFER_INTERVAL_MINUTES:-5}
      - DELETE_AFTER_DAYS=${DELETE_AFTER_DAYS:-1}
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  worker:
    image: ghcr.io/nicholasmparker/skylapse/worker:main
    command: rq worker --url redis://redis:6379 timelapse
    volumes:
      - skylapse-images:/data/images
      - skylapse-timelapses:/data/timelapses
      - skylapse-db:/data/db # SQLite database persistence
    depends_on:
      - redis
      - backend
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        limits:
          memory: 4G # Increase memory for large image processing

  frontend:
    image: ghcr.io/nicholasmparker/skylapse/frontend:main
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:8082}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  skylapse-images:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SKYLAPSE_IMAGES_PATH:-./data/images}
  skylapse-timelapses:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SKYLAPSE_TIMELAPSES_PATH:-./data/timelapses}
  skylapse-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SKYLAPSE_DB_PATH:-./data/db}
  redis-data:
