services:
  processing:
    build: ./processing
    ports:
      - "8081:8081"
    environment:
      - PYTHONUNBUFFERED=1

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8081
      - VITE_WS_URL=http://localhost:8081
      - VITE_CAPTURE_URL=http://helios.local:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - processing
