version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8082:8082"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - PI_HOST=helios.local
      - PI_PORT=8080

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_BACKEND_URL=http://localhost:8082
    depends_on:
      - backend