# Skylapse Processing Service Docker Compose Configuration

version: '3.8'

services:
  processing:
    build: .
    image: skylapse/processing:1.0.0-sprint1
    container_name: skylapse-processing
    restart: unless-stopped

    ports:
      - "8081:8081"  # API server

    volumes:
      # Persistent storage for processing
      - processing_data:/opt/skylapse/output
      - processing_temp:/tmp/skylapse_processing

      # Transfer directories (shared with capture service)
      - transfer_incoming:/tmp/skylapse_transfers/incoming
      - transfer_processing:/tmp/skylapse_transfers/processing
      - transfer_completed:/tmp/skylapse_transfers/completed

      # Logs
      - processing_logs:/var/log/skylapse

      # Configuration override (optional)
      - ./config/processing.yaml:/app/config/processing.yaml:ro

    environment:
      - SKYLAPSE_ENV=production
      - PYTHONUNBUFFERED=1

      # Processing configuration
      - MAX_CONCURRENT_JOBS=4
      - JOB_TIMEOUT_SECONDS=3600

      # Resource limits
      - OMP_NUM_THREADS=4
      - OPENCV_NUM_THREADS=4

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '1'

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

    # Network configuration
    networks:
      - skylapse

    # Security
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp

volumes:
  processing_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/skylapse/processing/data

  processing_temp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

  processing_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/skylapse/logs/processing

  # Transfer volumes (shared between services)
  transfer_incoming:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/skylapse/transfers/incoming

  transfer_processing:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/skylapse/transfers/processing

  transfer_completed:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/skylapse/transfers/completed

networks:
  skylapse:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
