# Arducam IMX519 16MP Camera Configuration
# Primary camera configuration for high-quality mountain timelapses

sensor:
  model: "IMX519"
  bayer_pattern: "RGGB"
  base_iso: 100
  max_iso: 800
  iso_invariance_point: 800
  max_exposure_us: 10000000  # 10 seconds maximum
  resolution_mp: 16.0
  max_resolution: [4656, 3496]
  sensor_size_mm: [7.4, 5.6]

optical:
  focal_length_mm: 4.28
  aperture: "f/2.0"
  hyperfocal_distance_mm: 1830  # For landscape focus
  focus_range_mm: [100.0, .inf]

  # Focus calibration points for landscape distances
  focus_calibration_points:
    - [.inf, 0.0]      # Infinity focus
    - [2000.0, 0.05]   # 2km focus
    - [1000.0, 0.12]   # 1km focus
    - [500.0, 0.25]    # 500m focus

processing:
  # Color processing
  color_matrix_daylight:
    - [1.654, -0.532, -0.122]
    - [-0.421, 1.842, -0.421]
    - [-0.089, -0.634, 1.723]

  # Demosaicing and noise reduction
  demosaic_algorithm: "DCB"  # Detail-preserving DCB
  spatial_nr_strength: 0.2
  temporal_nr_enabled: false  # No temporal NR for timelapses

  # Lens corrections
  barrel_distortion_k1: -0.042
  vignetting_correction: true
  chromatic_aberration_correction: true

capture:
  default_quality: 95
  default_format: "JPEG"
  enable_raw_capture: false  # DNG support for Phase 2
  capture_timeout_ms: 5000

  # HDR bracketing support
  hdr_bracket_stops: [-2, -1, 0, 1, 2]
  max_bracket_frames: 7

performance:
  capture_buffer_size: 4
  max_capture_latency_ms: 50
  focus_timeout_ms: 2000

  # Thermal management
  thermal_throttle_temp_c: 75
  cooling_delay_ms: 100

capabilities:
  - AUTOFOCUS
  - MANUAL_FOCUS
  - HDR_BRACKETING
  - RAW_CAPTURE
  - LIVE_PREVIEW

# Mountain-specific optimizations
mountain_presets:
  golden_hour:
    white_balance_k: 3200
    exposure_compensation: 0.3
    hdr_enabled: true

  blue_hour:
    white_balance_k: 8500
    iso_max: 800
    noise_reduction: 0.3

  overcast:
    exposure_compensation: 0.7
    contrast_boost: 0.2
    shadow_lift: 0.3

  stormy:
    exposure_compensation: -0.3
    highlight_protection: true
    capture_interval_fast: true