# Raspberry Pi Camera Module v3 Configuration
# Alternative camera support

sensor:
  model: "IMX708"
  bayer_pattern: "RGGB"
  base_iso: 100
  max_iso: 800
  iso_invariance_point: 400
  max_exposure_us: 10000000
  resolution_mp: 12.0
  max_resolution: [4608, 2592]
  sensor_size_mm: [7.9, 5.3]

optical:
  focal_length_mm: 2.75
  aperture: "f/1.8"
  hyperfocal_distance_mm: 950
  focus_range_mm: [140.0, .inf]

processing:
  color_matrix_daylight:
    - [1.543, -0.421, -0.122]
    - [-0.321, 1.652, -0.331]
    - [-0.119, -0.512, 1.631]

  demosaic_algorithm: "AHD"  # Different algorithm for this sensor
  spatial_nr_strength: 0.25

capture:
  default_quality: 95
  default_format: "JPEG"
  enable_raw_capture: false
  capture_timeout_ms: 5000

performance:
  capture_buffer_size: 4
  max_capture_latency_ms: 50
  focus_timeout_ms: 2000

capabilities:
  - AUTOFOCUS
  - MANUAL_FOCUS
  - HDR_BRACKETING
  - RAW_CAPTURE
  - LIVE_PREVIEW
