# Skylapse Processing Service Configuration

api:
  port: 8081
  cors_enabled: true
  max_request_size_mb: 100
  auth_enabled: false  # Phase 2 feature

processing:
  max_concurrent_jobs: 4
  job_timeout_seconds: 3600
  temp_dir: "/tmp/skylapse_processing"
  output_dir: "/opt/skylapse/output"

  # Job priorities and scheduling
  job_priorities:
    urgent: 0
    high: 1
    normal: 2
    low: 3
    background: 4

  # Resource management
  memory_limit_per_job_mb: 2048
  cpu_cores_per_job: 1

image:
  # Supported input formats
  supported_formats:
    - "JPEG"
    - "PNG"
    - "TIFF"
    - "BMP"
    # - "DNG"  # RAW format support in Phase 2

  # Processing parameters
  max_resolution: [4656, 3496]  # Arducam IMX519 max resolution

  quality_levels:
    high: 95
    medium: 85
    low: 75

  # Enhancement settings (Phase 1 stubs)
  enhancement:
    noise_reduction:
      enabled: false  # Phase 2
      algorithms: ["bilateral", "non_local_means"]
      default_strength: 0.3

    sharpening:
      enabled: false  # Phase 2
      unsharp_mask_radius: 1.0
      unsharp_mask_amount: 0.5

    color_correction:
      enabled: false  # Phase 2
      auto_white_balance: true
      contrast_enhancement: true

video:
  # Output format specifications
  output_formats:
    "480p":
      resolution: [854, 480]
      bitrate_mbps: 2

    "720p":
      resolution: [1280, 720]
      bitrate_mbps: 4

    "1080p":
      resolution: [1920, 1080]
      bitrate_mbps: 8

    "4k":
      resolution: [3840, 2160]
      bitrate_mbps: 20

  # Encoding settings
  encoding:
    default_framerate: 24.0
    codec: "h264"  # Phase 2 will add h265 support
    quality: "high"
    gpu_acceleration: false  # Phase 2 feature

  # Processing options (Phase 2)
  processing:
    stabilization_enabled: false
    deflickering_enabled: false
    color_grading_enabled: false

storage:
  # Cleanup settings
  cleanup_interval_hours: 24
  temp_retention_hours: 6
  output_retention_days: 30

  # File management
  max_disk_usage_pct: 80
  emergency_cleanup_threshold_pct: 90

transfer:
  # Directory configuration
  incoming_dir: "/tmp/skylapse_transfers/incoming"
  processing_dir: "/tmp/skylapse_transfers/processing"
  completed_dir: "/tmp/skylapse_transfers/completed"

  # Transfer monitoring
  check_interval_seconds: 30
  transfer_timeout_seconds: 300
  max_retry_attempts: 3

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # File logging
  file_enabled: true
  file_path: "/var/log/skylapse/processing.log"
  file_max_size_mb: 100
  file_backup_count: 5

  # Structured logging
  json_logging: false  # Phase 2 feature

monitoring:
  # Metrics collection
  metrics_enabled: true
  metrics_port: 8090

  # Performance tracking
  performance_tracking: true
  detailed_timing: false  # Debug mode

  # Health checks
  health_check_interval_seconds: 30

# Development settings
development:
  debug_mode: false
  mock_processing: false
  simulate_delays: false
  test_data_generation: false
